/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariantType } from "./components/atoms/button/types";
export { ButtonVariantType } from "./components/atoms/button/types";
export namespace Components {
    interface UiButton {
        /**
          * Specifies the alternative text for screen readers
         */
        "accesibleLabel"?: string;
        /**
          * Specifies if button is disabled
         */
        "disabled"?: boolean;
        /**
          * Specifies the link reference. If the property is filled the `a` element is rendered
         */
        "linkHref"?: string;
        /**
          * Specifies the link target.
         */
        "linkTarget"?: string;
        /**
          * Specifies the button variant
         */
        "variant"?: ButtonVariantType;
    }
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        /**
          * Specifies the alternative text for screen readers
         */
        "accesibleLabel"?: string;
        /**
          * Specifies if button is disabled
         */
        "disabled"?: boolean;
        /**
          * Specifies the link reference. If the property is filled the `a` element is rendered
         */
        "linkHref"?: string;
        /**
          * Specifies the link target.
         */
        "linkTarget"?: string;
        /**
          * Specifies the button variant
         */
        "variant"?: ButtonVariantType;
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
        }
    }
}
